// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package order

import (
	"context"
	"fmt"
)

type CreateOrderRequest struct {
	UserId   int64   `thrift:"user_id,1,required" frugal:"1,required,i64" json:"user_id"`
	Amount   float64 `thrift:"amount,2,required" frugal:"2,required,double" json:"amount"`
	ItemName string  `thrift:"item_name,3,required" frugal:"3,required,string" json:"item_name"`
}

func NewCreateOrderRequest() *CreateOrderRequest {
	return &CreateOrderRequest{}
}

func (p *CreateOrderRequest) InitDefault() {
}

func (p *CreateOrderRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *CreateOrderRequest) GetAmount() (v float64) {
	return p.Amount
}

func (p *CreateOrderRequest) GetItemName() (v string) {
	return p.ItemName
}
func (p *CreateOrderRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *CreateOrderRequest) SetAmount(val float64) {
	p.Amount = val
}
func (p *CreateOrderRequest) SetItemName(val string) {
	p.ItemName = val
}

func (p *CreateOrderRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderRequest(%+v)", *p)
}

var fieldIDToName_CreateOrderRequest = map[int16]string{
	1: "user_id",
	2: "amount",
	3: "item_name",
}

type CreateOrderResponse struct {
	OrderNo string `thrift:"order_no,1,required" frugal:"1,required,string" json:"order_no"`
	Status  string `thrift:"status,2,required" frugal:"2,required,string" json:"status"`
}

func NewCreateOrderResponse() *CreateOrderResponse {
	return &CreateOrderResponse{}
}

func (p *CreateOrderResponse) InitDefault() {
}

func (p *CreateOrderResponse) GetOrderNo() (v string) {
	return p.OrderNo
}

func (p *CreateOrderResponse) GetStatus() (v string) {
	return p.Status
}
func (p *CreateOrderResponse) SetOrderNo(val string) {
	p.OrderNo = val
}
func (p *CreateOrderResponse) SetStatus(val string) {
	p.Status = val
}

func (p *CreateOrderResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderResponse(%+v)", *p)
}

var fieldIDToName_CreateOrderResponse = map[int16]string{
	1: "order_no",
	2: "status",
}

type OrderService interface {
	CreateOrder(ctx context.Context, req *CreateOrderRequest) (r *CreateOrderResponse, err error)
}

type OrderServiceCreateOrderArgs struct {
	Req *CreateOrderRequest `thrift:"req,1" frugal:"1,default,CreateOrderRequest" json:"req"`
}

func NewOrderServiceCreateOrderArgs() *OrderServiceCreateOrderArgs {
	return &OrderServiceCreateOrderArgs{}
}

func (p *OrderServiceCreateOrderArgs) InitDefault() {
}

var OrderServiceCreateOrderArgs_Req_DEFAULT *CreateOrderRequest

func (p *OrderServiceCreateOrderArgs) GetReq() (v *CreateOrderRequest) {
	if !p.IsSetReq() {
		return OrderServiceCreateOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceCreateOrderArgs) SetReq(val *CreateOrderRequest) {
	p.Req = val
}

func (p *OrderServiceCreateOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceCreateOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCreateOrderArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceCreateOrderArgs = map[int16]string{
	1: "req",
}

type OrderServiceCreateOrderResult struct {
	Success *CreateOrderResponse `thrift:"success,0,optional" frugal:"0,optional,CreateOrderResponse" json:"success,omitempty"`
}

func NewOrderServiceCreateOrderResult() *OrderServiceCreateOrderResult {
	return &OrderServiceCreateOrderResult{}
}

func (p *OrderServiceCreateOrderResult) InitDefault() {
}

var OrderServiceCreateOrderResult_Success_DEFAULT *CreateOrderResponse

func (p *OrderServiceCreateOrderResult) GetSuccess() (v *CreateOrderResponse) {
	if !p.IsSetSuccess() {
		return OrderServiceCreateOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceCreateOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateOrderResponse)
}

func (p *OrderServiceCreateOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceCreateOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCreateOrderResult(%+v)", *p)
}

var fieldIDToName_OrderServiceCreateOrderResult = map[int16]string{
	0: "success",
}
